const availableResumeKeys = new Set([
    'phoneNumber',
    'firstName',
    'email',
    'profession',
    'city',
    'lastName',
    'industry',
    'country',
    'companyName',
    'certification',
    'authority',
    'certificationName',
    'jobTitle',
    'startDate',
    'endDate',
    'institution',
    'degree',
    'language',
    'description',
    'currentlyStudying',
    'skillName',
    'skillLevel',
]);

export { availableResumeKeys };
