const professionsSeed = [
    { profession: 'Accountant', industry_id: 1 },
    { profession: 'Financial Analyst', industry_id: 1 },
    { profession: 'Compliance Officer', industry_id: 1 },
    { profession: 'Banker', industry_id: 1 },
    { profession: 'Financial Advisor', industry_id: 1 },
    { profession: 'Loan Officer', industry_id: 1 },
    { profession: 'Auditing Clerk', industry_id: 1 },
    { profession: 'Accounting Assistant', industry_id: 1 },
    { profession: 'Finance Director', industry_id: 1 },
    { profession: 'Auditor', industry_id: 1 },
    { profession: 'Administrative', industry_id: 2 },
    { profession: 'Call Center Agent', industry_id: 2 },
    { profession: 'Administrative Assistant', industry_id: 2 },
    { profession: 'Office Administrator', industry_id: 2 },
    { profession: 'Receptionist', industry_id: 2 },
    { profession: 'Business Manager', industry_id: 2 },
    { profession: 'Office Secretary', industry_id: 2 },
    { profession: 'Office Manager', industry_id: 2 },
    { profession: 'Personal Assistant', industry_id: 2 },
    { profession: 'Web Developer', industry_id: 3 },
    { profession: 'Software Developer', industry_id: 3 },
    { profession: 'Data Analyst', industry_id: 3 },
    { profession: 'Data Scientist', industry_id: 3 },
    { profession: 'Software Engineer', industry_id: 3 },
    { profession: 'IT Manager', industry_id: 3 },
    { profession: 'Front-end Developer', industry_id: 3 },
    { profession: 'Computer Science', industry_id: 3 },
    { profession: 'Full Stack Developer', industry_id: 3 },
    { profession: 'Project Manager', industry_id: 3 },
    { profession: 'System Administrator', industry_id: 3 },
    { profession: 'QA Engineer', industry_id: 3 },
    { profession: 'DevOps Engineer', industry_id: 3 },
    { profession: 'System Analyst', industry_id: 3 },
    { profession: 'Java Developer', industry_id: 3 },
    { profession: 'Web Analyst', industry_id: 3 },
    { profession: 'Back-end Developer', industry_id: 3 },
    { profession: 'Human Resources Manager', industry_id: 4 },
    { profession: 'Recruiter', industry_id: 4 },
    { profession: 'HR Director', industry_id: 4 },
    { profession: 'Human Resources', industry_id: 4 },
    { profession: 'Product Manager', industry_id: 5 },
    { profession: 'Bussines Development Manager', industry_id: 5 },
    { profession: 'Consultant', industry_id: 5 },
    { profession: 'Program Manager', industry_id: 5 },
    { profession: 'CEO', industry_id: 5 },
    { profession: 'Project Coordinator', industry_id: 5 },
    { profession: 'Supervisor', industry_id: 5 },
    { profession: 'Product Owner', industry_id: 5 },
    { profession: 'CTO', industry_id: 5 },
    { profession: 'Lawyer', industry_id: 6 },
    { profession: 'Attorney', industry_id: 6 },
    { profession: 'Insurance Agent', industry_id: 6 },
    { profession: 'Art Director', industry_id: 7 },
    { profession: 'Editor', industry_id: 7 },
    { profession: 'Graphic Designer', industry_id: 7 },
    { profession: 'Interior Designer', industry_id: 7 },
    { profession: 'Civil Engineer', industry_id: 8 },
    { profession: 'Electrical Engineer', industry_id: 8 },
    { profession: 'Mechanical Engineer', industry_id: 8 },
    { profession: 'Research Engineer', industry_id: 8 },
    { profession: 'Agricultural Engineer', industry_id: 8 },
    { profession: 'Chemical Engineer', industry_id: 8 },
    { profession: 'Facilities Engineer', industry_id: 8 },
    { profession: 'Professor', industry_id: 9 },
    { profession: 'Principal', industry_id: 9 },
    { profession: 'Academic Tutor', industry_id: 9 },
    { profession: 'PhD', industry_id: 9 },
    { profession: 'Teacher', industry_id: 9 },
    { profession: 'Personal Trainer', industry_id: 9 },
    { profession: 'Sales Manager', industry_id: 10 },
    { profession: 'Sales Assistant', industry_id: 10 },
    { profession: 'Dentist', industry_id: 11 },
    { profession: 'Healthcare Administrator', industry_id: 11 },
    { profession: 'Nurse', industry_id: 11 },
    { profession: 'Therapist', industry_id: 11 },
    { profession: 'Pharmacist', industry_id: 11 },
    { profession: 'Physician', industry_id: 11 },
    { profession: 'Psychologist', industry_id: 11 },
    { profession: 'Veterinarian', industry_id: 11 },
    { profession: 'Digital Marketing Manager', industry_id: 12 },
    { profession: 'DContent Writer', industry_id: 12 },
    { profession: 'Marketing Manager', industry_id: 12 },
    { profession: 'Marketing Coordinator', industry_id: 12 },
    { profession: 'Marketing Analyst', industry_id: 12 },
];

export { professionsSeed };
