export {
    type Contacts,
    type Education,
    type Experience,
    type PersonalInformation,
    type Resume,
    type ResumeAiScoreRequestDto,
    type ResumeAiScoreResponseDto,
    type ResumeCreateItemRequestDto,
    type ResumeGetAllRequestDto,
    type ResumeGetAllResponseDto,
    type ResumeGetItemRequestDto,
    type ResumeGetItemResponseDto,
    type ResumeService,
    type ResumeUpdateItemRequestDto,
    type TechnicalSkill,
    ResumesApiPath,
    SkillLevel,
} from 'shared/build/index.js';
