enum AppRoute {
    ROOT = '/',
    LOG_IN = '/log-in',
    SIGN_UP = '/sign-up',
    PREVIEW = '/preview',
    PAYMENT = '/payment',
    PROFILE = '/profile',
    RESUME = '/resumes/:id',
    RESUME_EDIT = '/resumes/edit',
    RESUME_CREATE = '/resumes/create',
    RESUME_ACCESS = '/resumes/share/:id',
    HOME = '/home',
    TEMPLATES = '/templates',
    EMAIL_CONFIRMATION = '/email-confirmation',
    EMAIL_CONFIRMATION_SUCCESS = '/email-confirmation-success',
    EMAIL_CONFIRMATION_FAIL = '/email-confirmation-fail',
    STATISTICS = '/statistics',
    TEMPLATE = '/template',
    TEMPLATE_EDITOR = '/template-editor',
    CHECK_EMAIL = '/check-email',
    FORGOT_PASSWORD = '/forgot-password',
    QA = '/qa',
    SUBSCRIPTION_CANCEL = '/subscription-cancel',
}

export { AppRoute };
