enum IconName {
    PLUS = 'plus',
    CHEVRON_DOWN = 'chevron_down',
    GOOGLE = 'google',
    GITHUB = 'github',
    FACEBOOK = 'facebook',
    LINKEDIN = 'linkedin',
    EYE_OPEN = 'eye_open',
    EYE_SLASH = 'eye_slash',
    SEARCH = 'search_glass',
    ARROW_UP = 'arrow_up',
    ARROW_LEFT = 'arrow_left',
    ARROW_DOWN = 'arrow_down',
    CLOSE_CROSS = 'close_button',
    CREDIT_CARD = 'credit_card',
    CHECK = 'check',
    DOWNLOAD = 'download',
    FILE = 'file',
    SHIELD_ALT = 'shield_alt',
    CHAIN_BROKEN = 'chain_broken',
    DOOR_CLOSED = 'door_closed',
    CROWN = 'crown',
    SAVE = 'save',
    QUESTION_CIRCLE = 'circle_question',
    CHECK_CIRCLE = 'circle_check',
}

export { IconName };
