enum DatabaseTableName {
    MIGRATIONS = 'migrations',
    USERS = 'users',
    OAUTH_CONNECTIONS = 'oauth_connections',
    OAUTH_USERS = 'oauth_users',
    PROFILE = 'user_profile',
    PERSONAL_INFORMATION = 'personal_information',
    EXPERIENCE = 'experience',
    TECHNICAL_SKILLS = 'technical_skills',
    EDUCATION = 'education',
    CONTACT_DETAILS = 'contact_details',
    RESUMES = 'resumes',
    TEMPLATES = 'templates',
    USER_TEMPLATES = 'user_templates',
    REVIEWS = 'reviews',
    RECENTLY_VIEWED = 'recently_viewed',
    RESUME_SHARE_LINK = 'resume_share_link',
    RESUME_SHARE_ACCESS = 'resume_share_access',
    SUBSCRIPTION_PLANS = 'subscription_plans',
    CERTIFICATION = 'certification',
    LANGUAGES = 'languages',
    CUSTOM_SECTIONS = 'custom_sections',
}

export { DatabaseTableName };
